### ISSUE TITLE
Require Only App-Extension-Safe API

### ISSUE THREAD

**Issue by basememara** [onmyway133/Arcane#12]
I'm trying to use `Arcane` in a Swift framework that is used in iOS extensions like Today, Notifications, etc. However, I'm getting a warning in Xcode:

```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/.../Arcane.framework/Arcane
```

Can you please enable `Require Only App-Extension-Safe API` in the build settings?

**Comment by onmyway133** [comment]
@basememara Hi, I 've enabled it for you. Can you check https://github.com/onmyway133/Arcane/releases/tag/1.1.0 ?

**Comment by basememara** [comment]
This worked, thank you!!
