### ISSUE TITLE
How to lint this pod?

### ISSUE THREAD

**Issue by TienVu-PW** [onmyway133/Arcane#14]
Hi, I'm trying to integrate CommonCrypto into my Cocoapods project, I found yours and see how you do it, but when i do `pod lib lint`, it return error `no such module 'CCommonCrypto'`, so how can you lint and upload to pod base?

**Comment by jinlongyu123** [comment]
Hi, I'm trying to integrate CommonCrypto into my Cocoapods project, I found yours and see how you do it, but when i do pod lib lint, it return error no such module 'CCommonCrypto', so how can you lint and upload to pod base?

**Comment by onmyway133** [comment]
@TienVu-PW @jinlongyu123 Hi, sorry for late reply. For pods with modulemap, `pod lib lint` does not seem to work, but `pod spec lint` and simply `pod trunk push` works.
