### ISSUE TITLE
Random Data

### ISSUE THREAD

**Issue by kapizoli77** [onmyway133/Arcane#16]
It would be great, if you can implement a cryptographically safe random String (or at least Data) generation. Thanks! :)

**Comment by onmyway133** [comment]
@kapizoli77 Hi, this uses Common Crypto under the hood. For randomisation, you can use `Randomization Services` in `Security` framework https://developer.apple.com/documentation/security/randomization_services

**Comment by kapizoli77** [comment]
Thanks!
