### ISSUE TITLE
Possibly Incorrect Key Size for AES Encryption?

### ISSUE THREAD

**Issue by james-rant** [onmyway133/Arcane#17]
https://github.com/onmyway133/Arcane/blob/44c3013e0b93ad8d829f0e6a019e2c207cb4ef06/Sources/AES.swift#L48-L59

I'm by no means an expert, and I'm quite likely wrong, but when looking at the code linked above, it would appear to me that a 128-bit key size is incorrect when you specify a 32 Byte (256-bit) key data.

Is there perhaps something I'm not understanding?

**Comment by onmyway133** [comment]
@james-rantmedia Let's discuss over PR 😉
