### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by brightsider** [onmyway133/Arcane#7]
Can you provide Swift 3 update?

**Comment by onmyway133** [comment]
@brightsider Hi, thanks for asking. I plan to update it by the end of this week

**Comment by onmyway133** [comment]
@brightsider Hi, I just updated it to Swift 3. You can check the tag `0.5.0`

**Comment by brightsider** [comment]
@onmyway133 Thanks!

**Comment by onmyway133** [comment]
@brightsider I 'll close this for now. Feel free to reopen it if you have problem 😉

**Comment by brightsider** [comment]
I'm can't see this version in pod (
Unable to satisfy the following requirements:
- `Arcane (~> 0.5.0)` required by `Podfile`

**Comment by onmyway133** [comment]
@brightsider I can't publish pod with Swift 3 for now. Waiting for new version of cocoapods. So you must specify the `tag` in your Podfile as well

**Comment by brightsider** [comment]
You can use rc version for this.
Just use in terminal - echo 3.0 > .swift-version
And then with rc version upload pod
